version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=host.docker.internal  # Для доступу до локального MySQL
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/hrPlatform
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/hrPlatform/protocol/openid-connect/certs
    extra_hosts:
      - "keycloak:host-gateway"  # Важливо для Windows/Mac
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: ["start-dev"]